export const tripData = [
  {
    day: 1,
    date: "May 3, 2025",
    title: "Vancouver → Juniper Beach",
    from: "Vancouver",
    to: "Juniper Beach",
    departureTime: "8:00 AM",
    driveTime: "~3 hours",
    distance: 337,
    accommodation: "Campsite 24, Juniper Beach Provincial Park",
    accommodationType: "camping",
    accommodationDetails: "Reservation #BCIN26-1113826B1",
    hikes: [
      {
        name: "Thompson River Viewpoint & Juniper Bluff Trail",
        distance: "2 km",
        difficulty: "Easy",
        duration: "30 min",
        description: "A short evening hike with beautiful views of the Thompson River.",
      },
    ],
    notes:
      "Alternative: Drive 20 min to Cache Creek for Dinner at Rancher's Cookhouse & Heritage Trail stroll. Night Activity: Campfire & stargazing.",
    detailedNotes: {
      en: "🚗 **Our adventure begins!** We'll leave bright and early from Vancouver, hitting the scenic Trans-Canada Highway towards the drier interior. The drive offers changing landscapes, transitioning from coastal rainforest to grasslands.\n\n⛺ **Destination:** Juniper Beach Provincial Park, nestled beside the mighty Thompson River. After setting up camp at Site 24, we'll stretch our legs with a short evening hike on the Juniper Bluff Trail, enjoying panoramic views of the river valley as the sun begins to set.\n\n🍽️ **Dinner options:** Cooking at our campsite or taking a short drive to Cache Creek for a meal at the Rancher's Cookhouse followed by a walk along their Heritage Trail.\n\n🔥 **Evening:** The night concludes under the stars, hopefully with a crackling campfire (fire restrictions permitting). Perfect opportunity for stargazing in this low light-pollution area! 🌟",
      es: "🚗 **¡Nuestra aventura comienza!** Saldremos temprano de Vancouver, tomando la pintoresca autopista Transcanadiense hacia el interior más seco. El viaje ofrece paisajes cambiantes, pasando de la selva costera a las praderas.\n\n⛺ **Destino:** El Parque Provincial Juniper Beach, junto al caudaloso río Thompson. Después de instalar nuestro campamento en el Sitio 24, estiraremos las piernas con una corta caminata nocturna por el sendero Juniper Bluff, disfrutando de vistas panorámicas del valle del río mientras el sol comienza a ponerse.\n\n🍽️ **Opciones para cenar:** Cocinar en el campamento o conducir un corto trayecto hasta Cache Creek para comer en el Rancher's Cookhouse, seguido de un paseo por su sendero patrimonial.\n\n🔥 **Noche:** La noche concluye bajo las estrellas, con suerte con una fogata crepitante (si las restricciones de fuego lo permiten). ¡Perfecta oportunidad para observar estrellas en esta área con poca contaminación lumínica! 🌟",
    },
  },
  {
    day: 2,
    date: "May 4, 2025",
    title: "Juniper Beach → Revelstoke",
    from: "Juniper Beach",
    to: "Revelstoke",
    departureTime: "8:00 AM",
    driveTime: "3.5-4 hours",
    distance: 350,
    accommodation: "Airbnb in Revelstoke",
    accommodationType: "hotel",
    hikes: [
      {
        name: "Gibraltar Rock & Paul Lake Loop",
        distance: "5 km",
        difficulty: "Moderate",
        duration: "2 hrs",
        description: "Morning hike before continuing to Revelstoke.",
      },
    ],
    notes:
      "Evening: Explore downtown Revelstoke. Alternative accommodation options: Snowforest Campground or Blanket Creek Provincial Park.",
    detailedNotes: {
      en: "🥞 **Morning:** After breakfast at our scenic campsite, we'll pack up and head towards Kamloops.\n\n🥾 **First Adventure:** Before the main drive to Revelstoke, we'll embark on a morning hike around Paul Lake, tackling the Gibraltar Rock loop. This moderate 5km hike rewards us with stunning views of the turquoise lake waters and surrounding pine forests.\n\n🏞️ **Scenic Drive:** Once our hike is complete, we continue our journey eastward, following the highway as it winds through valleys and mountain passes towards Revelstoke. The landscape gradually shifts to more mountainous terrain, with snow-capped peaks appearing on the horizon.\n\n🏡 **Arrival:** Upon reaching the mountain town of Revelstoke, we'll check into our cozy Airbnb and settle in.\n\n🍷 **Evening Plans:** We'll spend the evening exploring the charming downtown area with its historic buildings, perhaps grabbing dinner at one of the local eateries known for mountain-inspired cuisine. The town has a wonderful laid-back mountain vibe! 🏔️",
      es: "🥞 **Mañana:** Después del desayuno en nuestro pintoresco campamento, empacaremos y nos dirigiremos hacia Kamloops.\n\n🥾 **Primera Aventura:** Antes del viaje principal a Revelstoke, nos embarcaremos en una caminata matutina alrededor del Lago Paul, abordando el circuito de Gibraltar Rock. Esta caminata moderada de 5km nos recompensa con impresionantes vistas de las aguas turquesas del lago y los bosques de pinos circundantes.\n\n🏞️ **Conducción Panorámica:** Una vez completada nuestra caminata, continuamos nuestro viaje hacia el este, siguiendo la carretera mientras serpentea a través de valles y pasos montañosos hacia Revelstoke. El paisaje cambia gradualmente a un terreno más montañoso, con picos nevados apareciendo en el horizonte.\n\n🏡 **Llegada:** Al llegar al pueblo montañoso de Revelstoke, nos registraremos en nuestro acogedor Airbnb y nos instalaremos.\n\n🍷 **Planes Nocturnos:** Pasaremos la noche explorando el encantador centro con sus edificios históricos, tal vez cenando en uno de los restaurantes locales conocidos por su cocina inspirada en la montaña. ¡El pueblo tiene un maravilloso ambiente relajado de montaña! 🏔️",
    },
  },
  {
    day: 3,
    date: "May 5, 2025",
    title: "Revelstoke → Banff + Calgary Evening",
    from: "Revelstoke",
    to: "Banff",
    departureTime: "9:00 AM",
    driveTime: "~3.5 hours",
    distance: 280,
    accommodation: "Moxy Banff",
    accommodationType: "hotel",
    accommodationDetails: "Check-in: May 5-7",
    hikes: [],
    notes:
      "Afternoon: Quick Bow Falls visit or Cascade Gardens stroll. Drive to Calgary: Leave Banff ~5 PM (90 km, 1 hr 15 min). Meeting: Dinner & French lesson with Karla's instructor in Calgary (~7 PM). Return: Drive back to Moxy Banff (arrive ~10 PM).",
    detailedNotes: {
      en: "🏔️ **Mountain Journey:** Today takes us into the heart of the Canadian Rockies! Leaving Revelstoke, we'll drive through Glacier National Park (conditions permitting for quick photo stops) and Yoho National Park, witnessing some of the most dramatic mountain scenery in Canada.\n\n🏨 **Arrival in Banff:** Finally arriving in Banff, we'll check into the stylish Moxy Banff hotel and quickly freshen up.\n\n🌊 **Afternoon Options:** We'll have a brief window to stretch our legs – maybe a quick visit to the impressive Bow Falls (a filming location for old Hollywood movies!) or a peaceful stroll through the meticulously maintained Cascade of Time Gardens near the Banff administration building.\n\n🚗 **Evening Journey:** The main event for the evening involves a scenic drive to Calgary (approx. 1h 15m) along the Trans-Canada Highway.\n\n🍽️ **Cultural Exchange:** In Calgary, we'll meet Karla's French instructor for dinner around 7 PM. This offers a unique chance to practice French conversation while enjoying delicious food!\n\n🌙 **Return:** After dinner and conversation, we'll drive back to Banff under the night sky, arriving at the hotel around 10 PM, ready for our Banff adventures to begin in earnest tomorrow! ✨",
      es: "🏔️ **Viaje Montañoso:** ¡Hoy nos adentramos en el corazón de las Rocosas Canadienses! Saliendo de Revelstoke, conduciremos a través del Parque Nacional Glacier (si las condiciones permiten paradas rápidas para fotos) y el Parque Nacional Yoho, presenciando algunos de los paisajes montañosos más dramáticos de Canadá.\n\n🏨 **Llegada a Banff:** Finalmente llegando a Banff, nos registraremos en el elegante hotel Moxy Banff y nos refrescaremos rápidamente.\n\n🌊 **Opciones para la Tarde:** Tendremos una breve ventana para estirar las piernas – tal vez una visita rápida a las impresionantes cataratas Bow (¡un lugar de filmación para películas antiguas de Hollywood!) o un paseo tranquilo por los meticulosamente mantenidos Jardines Cascade of Time cerca del edificio de administración de Banff.\n\n🚗 **Viaje Nocturno:** El evento principal de la noche implica un viaje panorámico a Calgary (aprox. 1h 15m) a lo largo de la autopista Transcanadiense.\n\n🍽️ **Intercambio Cultural:** En Calgary, nos encontraremos con el instructor de francés de Karla para cenar alrededor de las 7 PM. ¡Esto ofrece una oportunidad única para practicar conversación en francés mientras disfrutamos de deliciosa comida!\n\n🌙 **Regreso:** Después de la cena y la conversación, conduciremos de regreso a Banff bajo el cielo nocturno, llegando al hotel alrededor de las 10 PM, ¡listos para que nuestras aventuras en Banff comiencen en serio mañana! ✨",
    },
  },
  {
    day: 4,
    date: "May 6, 2025",
    title: "Full Banff Exploration",
    from: "Banff",
    to: "Banff",
    departureTime: "9:00 AM",
    driveTime: "N/A",
    distance: 0,
    accommodation: "Moxy Banff",
    accommodationType: "hotel",
    hikes: [
      {
        name: "Johnston Canyon Trail",
        distance: "5.1 km (to Upper Falls)",
        difficulty: "Easy-Moderate",
        duration: "2-2.5 hrs",
        description: "Iconic hike along catwalks to stunning waterfalls.",
      },
    ],
    notes:
      "Midday: Lunch in Banff town. Afternoon: Banff Gondola & Summit Walk (Sulphur Mountain). Optional Side-Trip: Cave & Basin National Historic Site.",
    detailedNotes: {
      en: "🥾 **Morning Adventure:** A full day dedicated to experiencing the wonders of Banff! We'll start with a morning hike through Johnston Canyon, walking along elevated catwalks suspended over the rushing creek. The metal walkways cling to the limestone cliffs as we journey deeper into the canyon.\n\n💦 **Natural Wonders:** We'll witness both the Lower Falls (1.1 km from trailhead) and continue to the more dramatic Upper Falls (2.7 km from trailhead) – a truly iconic Banff experience with thundering water carving through ancient rock.\n\n🍽️ **Local Flavors:** Afterward, we'll head back to Banff town for lunch, soaking in the atmosphere of this charming mountain town nestled between towering peaks. Options range from casual cafés to mountain-inspired cuisine.\n\n🚡 **Aerial Views:** The afternoon is reserved for breathtaking panoramas from the top of Sulphur Mountain via the Banff Gondola. The enclosed gondola whisks us up to 2,281 meters elevation in just 8 minutes!\n\n🏔️ **Summit Experience:** We'll walk the summit boardwalk, enjoying 360° vistas of six mountain ranges, the Bow Valley, and the town of Banff far below. The perspective from up here is absolutely stunning!\n\n🏛️ **Historical Option:** If time and interest permit, we could also squeeze in a visit to the Cave & Basin National Historic Site, the birthplace of Canada's national parks system, featuring natural hot springs and fascinating exhibits about the area's development. 🌟",
      es: "🥾 **Aventura Matutina:** ¡Un día completo dedicado a experimentar las maravillas de Banff! Comenzaremos con una caminata matutina por Johnston Canyon, caminando por pasarelas elevadas suspendidas sobre el arroyo caudaloso. Los caminos metálicos se aferran a los acantilados de piedra caliza mientras nos adentramos más en el cañón.\n\n💦 **Maravillas Naturales:** Presenciaremos tanto las Cataratas Inferiores (1.1 km desde el inicio del sendero) y continuaremos hasta las más dramáticas Cataratas Superiores (2.7 km desde el inicio del sendero) – una experiencia verdaderamente icónica de Banff con agua atronadora tallando la roca antigua.\n\n🍽️ **Sabores Locales:** Después, regresaremos al pueblo de Banff para almorzar, absorbiendo la atmósfera de este encantador pueblo de montaña entre picos imponentes. Las opciones van desde cafés casuales hasta cocina inspirada en la montaña.\n\n🚡 **Vistas Aéreas:** La tarde está reservada para panoramas impresionantes desde la cima de Sulphur Mountain a través del teleférico de Banff. ¡La góndola cerrada nos lleva hasta 2,281 metros de elevación en solo 8 minutos!\n\n🏔️ **Experiencia en la Cumbre:** Caminaremos por el paseo marítimo de la cumbre, disfrutando de vistas de 360° de seis cordilleras, el Valle Bow y el pueblo de Banff muy abajo. ¡La perspectiva desde aquí es absolutamente impresionante!\n\n🏛️ **Opción Histórica:** Si el tiempo y el interés lo permiten, también podríamos incluir una visita al Sitio Histórico Nacional Cave & Basin, el lugar de nacimiento del sistema de parques nacionales de Canadá, con aguas termales naturales y exhibiciones fascinantes sobre el desarrollo del área. 🌟",
    },
  },
  {
    day: 5,
    date: "May 7, 2025",
    title: "More Banff Hikes & Lake Louise + KARLA'S BIRTHDAY!",
    from: "Banff",
    to: "Banff",
    departureTime: "8:00 AM",
    driveTime: "N/A (local driving)",
    distance: 0,
    accommodation: "Moxy Banff",
    accommodationType: "hotel",
    hikes: [
      {
        name: "Lake Agnes Tea House Trail",
        distance: "7.4 km",
        difficulty: "Moderate",
        duration: "3-4 hrs",
        description: "Classic hike starting from Lake Louise to a historic tea house.",
      },
      {
        name: "Tunnel Mountain Summit",
        distance: "4.5 km",
        difficulty: "Moderate",
        duration: "1.5-2 hrs",
        description: "Panoramic views of Banff townsite and Bow Valley.",
      },
      {
        name: "Bow Falls Viewpoint",
        distance: "<1 km",
        difficulty: "Easy",
        duration: "15-30 min",
        description: "Easy access viewpoint of powerful falls near town.",
      },
    ],
    notes: "HAPPY BIRTHDAY KARLA! Focus on Lake Agnes hike from Lake Louise. Choose afternoon options based on energy/time. Birthday dinner celebration in Banff!",
    detailedNotes: {
      en: "🎂 **HAPPY BIRTHDAY, KARLA!** 🎉 Today is all about celebrating your special day in one of the most beautiful places in the world!\n\n💎 **Lake Louise Morning:** We'll start your birthday with one of the most famous natural jewels: Lake Louise! We'll drive there early (approx. 45 min from Banff) to secure parking and start your day with the postcard-perfect view of the emerald lake backed by Victoria Glacier.\n\n🥾 **Iconic Hike:** We'll tackle the iconic hike up to the Lake Agnes Tea House. This moderate climb winds through forests of spruce and fir, passing Mirror Lake along the way, and offering increasing glimpses of the valley below.\n\n☕ **Historic Tea House:** The trail culminates at a charming, historic tea house nestled beside Lake Agnes at 2,135m elevation (built in 1901!). Here, we can enjoy a well-deserved hot drink and homemade treats with incredible views (bring cash for tea/snacks! No cards accepted).\n\n🏞️ **Lake Louise Shores:** After descending, we'll spend some time admiring Lake Louise itself, perhaps walking along its shoreline or simply relaxing by the impossibly blue waters.\n\n🌄 **Afternoon Options:** Depending on our energy levels and time, the afternoon offers choices:\n• A hike up Tunnel Mountain for excellent views overlooking Banff town and the surrounding valleys (moderate, 4.5km round trip)\n• An easy walk to the Bow Falls Viewpoint\n• Simply relaxing and exploring Banff town's shops and cafes\n\n🎁 **Birthday Celebration:** The evening will be dedicated to your birthday celebration! We'll enjoy a special dinner at one of Banff's finest restaurants, complete with cake, candles, and perhaps a small gift exchange. A perfect way to mark this milestone surrounded by the stunning beauty of the Canadian Rockies! 💝",
      es: "🎂 **¡FELIZ CUMPLEAÑOS, KARLA!** 🎉 ¡Hoy es todo sobre celebrar tu día especial en uno de los lugares más hermosos del mundo!\n\n💎 **Mañana en Lago Louise:** ¡Comenzaremos tu cumpleaños con una de las joyas naturales más famosas: el Lago Louise! Conduciremos temprano (aprox. 45 min desde Banff) para asegurar estacionamiento y comenzar tu día con la vista perfecta de postal del lago esmeralda respaldado por el Glaciar Victoria.\n\n🥾 **Caminata Icónica:** Abordaremos la icónica caminata hasta la Casa de Té del Lago Agnes. Esta subida moderada serpentea a través de bosques de abetos, pasando por el Lago Mirror en el camino, y ofreciendo vistas crecientes del valle abajo.\n\n☕ **Casa de Té Histórica:** El sendero culmina en una encantadora e histórica casa de té junto al lago Agnes a 2,135m de elevación (¡construida en 1901!). Aquí, podemos disfrutar de una merecida bebida caliente y delicias caseras con vistas increíbles (¡trae efectivo para té/bocadillos! No se aceptan tarjetas).\n\n🏞️ **Orillas del Lago Louise:** Después de descender, pasaremos un tiempo admirando el propio Lago Louise, quizás caminando a lo largo de su orilla o simplemente relajándonos junto a las aguas imposiblemente azules.\n\n🌄 **Opciones para la Tarde:** Dependiendo de nuestros niveles de energía y tiempo, la tarde ofrece opciones:\n• Una caminata hasta Tunnel Mountain para excelentes vistas sobre el pueblo de Banff y los valles circundantes (moderada, 4.5km ida y vuelta)\n• Una caminata fácil al mirador de Bow Falls\n• Simplemente relajarnos y explorar las tiendas y cafés del pueblo de Banff\n\n🎁 **Celebración de Cumpleaños:** ¡La noche estará dedicada a tu celebración de cumpleaños! Disfrutaremos de una cena especial en uno de los mejores restaurantes de Banff, completa con pastel, velas y quizás un pequeño intercambio de regalos. ¡Una forma perfecta de marcar este hito rodeado de la impresionante belleza de las Montañas Rocosas Canadienses! 💝"
    },
  },
  {
    day: 6,
    date: "May 8, 2025",
    title: "Banff → Revelstoke via Golden & Yoho",
    from: "Banff",
    to: "Revelstoke",
    departureTime: "8:00 AM",
    driveTime: "~4 hours (plus stops)",
    distance: 350,
    accommodation: "Airbnb in Revelstoke",
    accommodationType: "hotel",
    accommodationDetails: "Alternative: Repeat camp at Snowforest or Blanket Creek",
    hikes: [
      {
        name: "Emerald Lake Loop (Yoho NP)",
        distance: "5.2 km",
        difficulty: "Easy",
        duration: "1.5-2 hrs",
        description: "Stunningly beautiful, easy walk around the vibrant Emerald Lake.",
      },
      {
        name: "Golden Rotary Trails",
        distance: "Variable (up to 7km+)",
        difficulty: "Easy",
        duration: "1-2 hrs",
        description: "Pleasant riverside walk in Golden for a break.",
      },
    ],
    notes: "Travel west via Trans-Canada Highway. Key stops: Emerald Lake in Yoho NP and a break in Golden.",
    detailedNotes: {
      en: "👋 **Farewell for Now:** We bid farewell to Banff (for now!) and head west back towards Revelstoke. Our route takes us again through some of the most spectacular mountain landscapes in North America.\n\n🏞️ **Yoho National Park:** Our journey leads through Yoho National Park, where our primary stop will be the breathtaking Emerald Lake. It's named for its striking color, caused by rock flour carried into the lake from surrounding glaciers.\n\n🥾 **Lake Loop:** We'll enjoy an easy, scenic 5.2km walk around the entire lake, circling through old-growth forests on well-maintained paths while admiring the lake's vivid turquoise-green color and the surrounding mountains perfectly reflected in the water. Watch for wildlife – the area is home to moose, bears, and numerous bird species!\n\n🍽️ **Golden Stop:** Continuing west, we'll make a stop in the town of Golden for lunch. This railway and logging town sits at the confluence of the Columbia and Kicking Horse rivers, surrounded by mountains.\n\n🌊 **River Walk:** After our meal, we'll enjoy a relaxing stroll along the Golden Rotary Trails beside the rushing Kicking Horse River, with views of the surrounding peaks and charming red-roofed town.\n\n🚗 **Final Leg:** With our batteries recharged, we complete the final leg of the drive to Revelstoke through more spectacular mountain scenery, checking back into our cozy Airbnb for the night. 🌙",
      es: "👋 **Despedida por Ahora:** Nos despedimos de Banff (¡por ahora!) y nos dirigimos hacia el oeste de regreso a Revelstoke. Nuestra ruta nos lleva nuevamente a través de algunos de los paisajes montañosos más espectaculares de América del Norte.\n\n🏞️ **Parque Nacional Yoho:** Nuestro viaje nos lleva a través del Parque Nacional Yoho, donde nuestra parada principal será el impresionante Lago Esmeralda. Recibe su nombre por su sorprendente color, causado por la harina de roca llevada al lago desde los glaciares circundantes.\n\n🥾 **Vuelta al Lago:** Disfrutaremos de una caminata fácil y panorámica de 5.2km alrededor de todo el lago, circulando a través de bosques antiguos en senderos bien mantenidos mientras admiramos el vívido color turquesa-verde del lago y las montañas circundantes perfectamente reflejadas en el agua. ¡Atento a la vida silvestre – la zona es hogar de alces, osos y numerosas especies de aves!\n\n🍽️ **Parada en Golden:** Continuando hacia el oeste, haremos una parada en el pueblo de Golden para almorzar. Este pueblo ferroviario y maderero se encuentra en la confluencia de los ríos Columbia y Kicking Horse, rodeado de montañas.\n\n🌊 **Paseo por el Río:** Después de nuestra comida, disfrutaremos de un paseo relajante por los senderos Golden Rotary junto al caudaloso río Kicking Horse, con vistas a los picos circundantes y al encantador pueblo de techos rojos.\n\n🚗 **Tramo Final:** Con nuestras baterías recargadas, completamos el último tramo del viaje a Revelstoke a través de más espectacular paisaje montañoso, registrándonos nuevamente en nuestro acogedor Airbnb para pasar la noche. 🌙",
    },
  },
  {
    day: 7,
    date: "May 9, 2025",
    title: "Revelstoke → Kelowna (Birthday Eve!)",
    from: "Revelstoke",
    to: "Kelowna",
    departureTime: "10:00 AM",
    driveTime: "~3 hours (direct)",
    distance: 200,
    accommodation: "Cousin Elaine's Home in Kelowna",
    accommodationType: "family",
    hikes: [
      {
        name: "Inspiration Woods Trail",
        distance: "~2.5 km",
        difficulty: "Easy",
        duration: "1 hr",
        description: "Gentle forest walk before leaving Revelstoke.",
      },
    ],
    notes: "Family stay with cousin Elaine. Birthday Eve!",
    detailedNotes: {
      en: "🍳 **Final Morning:** Our last travel day begins with a relaxed breakfast with Elaine, savoring our final moments in the sunny Okanagan before we need to pack up and say our goodbyes.\n\n🛣️ **Highway Adventure:** We'll take the famous Coquihalla Highway (Highway 5) back to Vancouver, known for its dramatic mountain passes and engineering feats. This spectacular route is even featured on the TV show 'Highway Thru Hell' for its sometimes challenging conditions (though May should be pleasant)!\n\n🏔️ **Mountain Passes:** The highway climbs through impressive valleys and over high mountain passes, reaching elevations over 1,200 meters. The landscape transforms multiple times – from Okanagan Valley to highland plateau to coastal mountains. We'll cross the Great Bear snowshed, a massive concrete tunnel protecting the highway from avalanches!\n\n☕ **Rest Stop:** We can plan a brief stop in the town of Hope – known as the \"Chainsaw Carving Capital\" and filming location for First Blood (the first Rambo movie!). It's a perfect place for coffee and to stretch our legs before the final stretch.\n\n🏙️ **Return Journey:** The final leg of our drive takes us through the Fraser Valley and back to the coast, completing our circular journey through British Columbia. We'll arrive back in Vancouver by mid-afternoon, filled with memories of our adventure spanning mountains, lakes, forests, and a perfect birthday celebration! 🎂🚗✨",
      es: "🍳 **Última Mañana:** Nuestro último día de viaje comienza con un desayuno relajado con Elaine, saboreando nuestros últimos momentos en el soleado Okanagan antes de que necesitemos empacar y despedirnos.\n\n🛣️ **Aventura en la Autopista:** Tomaremos la famosa autopista Coquihalla (Carretera 5) de regreso a Vancouver, conocida por sus espectaculares pasos de montaña y hazañas de ingeniería. ¡Esta ruta espectacular incluso aparece en el programa de televisión 'Highway Thru Hell' por sus condiciones a veces desafiantes (aunque mayo debería ser agradable)!\n\n🏔️ **Pasos de Montaña:** La autopista sube a través de impresionantes valles y sobre altos pasos de montaña, alcanzando elevaciones de más de 1,200 metros. El paisaje se transforma múltiples veces – desde el Valle de Okanagan hasta la meseta de las tierras altas y las montañas costeras. ¡Cruzaremos el cobertizo de nieve Great Bear, un túnel masivo de concreto que protege la autopista de las avalanchas!\n\n☕ **Parada de Descanso:** Podemos planear una breve parada en el pueblo de Hope – conocido como la \"Capital de Tallado con Motosierra\" y lugar de filmación de First Blood (¡la primera película de Rambo!). Es un lugar perfecto para tomar un café y estirar las piernas antes del tramo final.\n\n🏙️ **Viaje de Regreso:** El último tramo de nuestro viaje nos lleva a través del Valle de Fraser y de regreso a la costa, completando nuestro viaje circular a través de Columbia Británica. Llegaremos de vuelta a Vancouver a media tarde, ¡llenos de recuerdos de nuestra aventura que abarca montañas, lagos, bosques y una perfecta celebración de cumpleaños! 🎂🚗✨",
    },
  },
  {
    day: 8,
    date: "May 10, 2025",
    title: "Kelowna Adventures & BIRTHDAY!",
    from: "Kelowna",
    to: "Kelowna",
    departureTime: "9:00 AM",
    driveTime: "N/A",
    distance: 0,
    accommodation: "Cousin Elaine's Home in Kelowna",
    accommodationType: "family",
    hikes: [
      {
        name: "Knox Mountain Park (Apex Trail)",
        distance: "~4 km",
        difficulty: "Moderate",
        duration: "1.5-2 hrs",
        description: "Hike for panoramic views of Kelowna and Okanagan Lake.",
      },
    ],
    notes: "HAPPY BIRTHDAY KARLA! Morning hike, afternoon winery visit or lakefront exploration. Birthday dinner/celebration with Elaine.",
    detailedNotes: {
      en: "🎂 **HAPPY BIRTHDAY, KARLA!** 🎉 Today is all about celebrating your special day in one of British Columbia's most beautiful regions!\n\n🥾 **Morning Adventure:** We'll start the day with some activity and great views, hiking the Apex Trail in Knox Mountain Park overlooking Kelowna and the vast Okanagan Lake. This 4km trail climbs to a spectacular viewpoint where you can see the entire city, lake, and surrounding vineyards and orchards stretching into the distance.\n\n🍷 **Afternoon Options:** After the hike, the afternoon is flexible and tailored to birthday wishes! We could:\n• Explore one of the many renowned local wineries for a tasting (the region is famous for its wine production!)\n• Stroll along the beautiful waterfront path by Okanagan Lake, visiting parks and beaches\n• Explore downtown Kelowna's shops and cafés\n• Simply relax at Elaine's and enjoy the Okanagan sunshine\n\n🎁 **Evening Celebration:** The evening will be dedicated to proper birthday festivities with Cousin Elaine! We'll enjoy a special dinner (either home-cooked or at a local restaurant of Karla's choosing), complete with cake, candles, and perhaps a small gift exchange. A perfect way to mark this milestone surrounded by beautiful scenery and family love! 💝",
      es: "🎂 **¡FELIZ CUMPLEAÑOS, KARLA!** 🎉 ¡Hoy es todo sobre celebrar tu día especial en una de las regiones más hermosas de Columbia Británica!\n\n🥾 **Aventura Matutina:** Comenzaremos el día con algo de actividad y excelentes vistas, caminando por el sendero Apex en Knox Mountain Park con vistas a Kelowna y al vasto lago Okanagan. Este sendero de 4km sube hasta un mirador espectacular donde puedes ver toda la ciudad, el lago y los viñedos y huertos circundantes que se extienden en la distancia.\n\n🍷 **Opciones para la Tarde:** Después de la caminata, ¡la tarde es flexible y adaptada a los deseos de cumpleaños! Podríamos:\n• Explorar una de las muchas bodegas locales de renombre para una degustación (¡la región es famosa por su producción de vino!)\n• Pasear por el hermoso camino frente al lago Okanagan, visitando parques y playas\n• Explorar las tiendas y cafés del centro de Kelowna\n• Simplemente relajarnos en casa de Elaine y disfrutar del sol de Okanagan\n\n🎁 **Celebración Nocturna:** ¡La noche estará dedicada a las festividades propias de cumpleaños con la prima Elaine! Disfrutaremos de una cena especial (ya sea casera o en un restaurante local de elección de Karla), completa con pastel, velas y quizás un pequeño intercambio de regalos. ¡Una forma perfecta de marcar este hito rodeado de hermoso paisaje y amor familiar! 💝",
    },
  },
  {
    day: 9,
    date: "May 11, 2025",
    title: "Kelowna → Vancouver",
    from: "Kelowna",
    to: "Vancouver",
    departureTime: "9:00 AM",
    driveTime: "~4 hours (via Coquihalla)",
    distance: 390,
    accommodation: "Home",
    accommodationType: "home",
    hikes: [],
    notes: "Breakfast with Elaine, then scenic drive back to Vancouver via the Coquihalla Highway (Hwy 5). Optional stop in Hope for coffee/stretch.",
    detailedNotes: {
      en: "🍳 **Final Morning:** Our last travel day begins with a relaxed breakfast with Elaine, savoring our final moments in the sunny Okanagan before we need to pack up and say our goodbyes.\n\n🛣️ **Highway Adventure:** We'll take the famous Coquihalla Highway (Highway 5) back to Vancouver, known for its dramatic mountain passes and engineering feats. This spectacular route is even featured on the TV show 'Highway Thru Hell' for its sometimes challenging conditions (though May should be pleasant)!\n\n🏔️ **Mountain Passes:** The highway climbs through impressive valleys and over high mountain passes, reaching elevations over 1,200 meters. The landscape transforms multiple times – from Okanagan Valley to highland plateau to coastal mountains. We'll cross the Great Bear snowshed, a massive concrete tunnel protecting the highway from avalanches!\n\n☕ **Rest Stop:** We can plan a brief stop in the town of Hope – known as the \"Chainsaw Carving Capital\" and filming location for First Blood (the first Rambo movie!). It's a perfect place for coffee and to stretch our legs before the final stretch.\n\n🏙️ **Return Journey:** The final leg of our drive takes us through the Fraser Valley and back to the coast, completing our circular journey through British Columbia. We'll arrive back in Vancouver by mid-afternoon, filled with memories of our adventure spanning mountains, lakes, forests, and a perfect birthday celebration! 🎂🚗✨",
      es: "🍳 **Última Mañana:** Nuestro último día de viaje comienza con un desayuno relajado con Elaine, saboreando nuestros últimos momentos en el soleado Okanagan antes de que necesitemos empacar y despedirnos.\n\n🛣️ **Aventura en la Autopista:** Tomaremos la famosa autopista Coquihalla (Carretera 5) de regreso a Vancouver, conocida por sus espectaculares pasos de montaña y hazañas de ingeniería. ¡Esta ruta espectacular incluso aparece en el programa de televisión 'Highway Thru Hell' por sus condiciones a veces desafiantes (aunque mayo debería ser agradable)!\n\n🏔️ **Pasos de Montaña:** La autopista sube a través de impresionantes valles y sobre altos pasos de montaña, alcanzando elevaciones de más de 1,200 metros. El paisaje se transforma múltiples veces – desde el Valle de Okanagan hasta la meseta de las tierras altas y las montañas costeras. ¡Cruzaremos el cobertizo de nieve Great Bear, un túnel masivo de concreto que protege la autopista de las avalanchas!\n\n☕ **Parada de Descanso:** Podemos planear una breve parada en el pueblo de Hope – conocido como la \"Capital de Tallado con Motosierra\" y lugar de filmación de First Blood (¡la primera película de Rambo!). Es un lugar perfecto para tomar un café y estirar las piernas antes del tramo final.\n\n🏙️ **Viaje de Regreso:** El último tramo de nuestro viaje nos lleva a través del Valle de Fraser y de regreso a la costa, completando nuestro viaje circular a través de Columbia Británica. Llegaremos de vuelta a Vancouver a media tarde, ¡llenos de recuerdos de nuestra aventura que abarca montañas, lagos, bosques y una perfecta celebración de cumpleaños! 🎂��✨",
    },
  },
]
